
version: '3'
services:
  app:
    image: uxhaloory/university-teacher-admin-account
    env_file: .env
    ports:
      - "8080"
    volumes:
      - ./target/:/usr/app/
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: backend
      SERVICE_CHECK_HTTP: /health/ready
      SERVICE_CHECK_INTERVAL: 5s
      SERVICE_CHECK_TIMEOUT: 3s
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    network_mode: host
    ports:
      - 8500:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - "app"
    command: "-cleanup=true -ip ${HOST_IP} consul://consul.service.consul:8500"
